### ISSUE TITLE
Open default IDE?

### ISSUE THREAD

**Issue by adamfratino** [sindresorhus/open#25]
I was just wondering if this was possible. Some people on our team use Atom, others Sublime, and I'd like to use opn to open the project directory (root folder, i.e. '.') in the user's default IDE.

**Comment by watson** [comment]
The environment variable `EDITOR` is sometimes used to specify the users default editor. If your team have that environment variable populated, you could do something like this:

```js
// open cwd in the editor
opn('./', {app: process.env.EDITOR})
```

**Comment by SamVerschueren** [comment]
On my laptop, `$ opn file.js` opens in my default editor. (Mac OS X)

**Comment by watson** [comment]
@SamVerschueren that's because your editor is set up to open file with the `.js` file extension I guess. But if you just write `$ opn /path/to/code/base` I think it would just open the folder in the Finder.app

**Comment by SamVerschueren** [comment]
@watson you're correct.

I don't it's a good idea to let `opn` open directories with the default editor (Sublime, Atom, ...). If you want that, you can always provide the application that should be used to open the directory as documented in [opn-cli](https://github.com/sindresorhus/opn-cli).

Or you could just create a function in your `.bash_profile` that does it for you.

```
# Visual Studio Code
code () {
    VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;
}
```

```
$ code .
```

Will open my current directory in VS Code.

**Comment by 88mpg** [comment]
Thanks for the replies.

The reason I'd like to open the project directory with open is because the task is intended to run when the project's watch task is started, i.e. "gulp watch open" would launch a webserver, then open the local page in your browser and the project in your IDE. It's obviously not a requirement to the project, just thought it'd be nice to have.

TBH, just running "atom ." or "subl ." is enough if I just want to open the project directory in an IDE from the command line.

**Comment by watson** [comment]
@88mpg If no `EDITOR` environment variable is set up, you could fall back to check if either `atom` or `subl` existed on the file system and use which ever one existed

**Comment by hollowdoor** [comment]
I might have to create a new issue because this is only partially related, but what about at least adding an option that would allow a terminal editor. Like https://github.com/sindresorhus/open-editor/blob/bb927327a3dbfc51a166041ef727de36e5fe85d3/index.js#L59

I could use [open-editor](https://github.com/sindresorhus/open-editor), but that module doesn't have a wait option.

**Comment by sindresorhus** [comment]
> I could use open-editor, but that module doesn't have a wait option.

Open an issue on `open-editor` about that.

**Comment by sindresorhus** [comment]
I don't plan to add support for editors here. Just use: https://github.com/sindresorhus/open-editor
