### ISSUE TITLE
wait doesn't work on macOS

### ISSUE THREAD

**Issue by kbrgl** [sindresorhus/open#92]
`wait` doesn't seem to work on macOS. With an image file opened in Preview, the Promise fulfills only when the app is quit using `Cmd+Q`, and __not when the window with the image is closed__.

To reproduce:
```js
opn("image.png").then(() => {
  // Won't run until Preview.app is quit with Cmd+Q
  console.log("Image viewer closed.")
}
```

I'm running `opn` on Electron.

**Comment by sindresorhus** [comment]
From the docs:

> Wait for the **opened app** to exit before fulfilling the promise.

As far as I know, there's no way to wait for a window of the app to close.

**Comment by starpit** [comment]
interesting. the oddity here is that if i specify `wait:true`, then `opn` never resolves, because it cannot observe window closure; but if i specify `wait:false`, then `opn` resolves before the open actually finishes, thus resulting in the desired open possibly not occurring, as the process may exit before `opn` has time to complete the requested opening.

on maOS, doesn't doesn't `open`, without the `-W` flag, return immediately upon completion? thus, it seems like `opn` should at least wait for `open` to return, before resolving...
